services:
  - type: web
    name: backend-results
    env: python
    # REMOVE postBuildCommand: "./post_deploy.sh"
    buildCommand: "./build.sh" # CHANGE THIS LINE
    startCommand: gunicorn app:app
    envVars: []
