services:
  - type: web
    name: backend-results
    env: python
    buildCommand: "./post_deploy.sh"
    # Explicitly bind Gunicorn to the Render-provided $PORT
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      # These variables should be set securely in the Render dashboard UI, NOT here.
      # - key: SENTRY_DSN
      #   value: This should be set in Render dashboard
      # - key: SENDER_EMAIL
      #   value: This should be set in Render dashboard
      # - key: EMAIL_APP_PASSWORD
      #   value: This should be set in Render dashboard
      # - key: FIREBASE_CREDENTIALS
      #   value: This should be set in Render dashboard

      # Render automatically provides the PORT environment variable.
      # You might explicitly define it here or in the dashboard for clarity, e.g.:
      - key: PORT
        value: 10000 # Render's default port.
      
      # REMOVED: SPACY_DATA environment variable.
