services:
  - type: web
    name: backend-results
    env: python
    buildCommand: "./post_deploy.sh"
    startCommand: gunicorn app:app
    envVars:
      # These variables should be set securely in the Render dashboard UI, NOT here.
      # - key: SENTRY_DSN
      #   value: This should be set in Render dashboard
      # - key: SENDER_EMAIL
      #   value: This should be set in Render dashboard
      # - key: EMAIL_APP_PASSWORD
      #   value: This should be set in Render dashboard
      # - key: FIREBASE_CREDENTIALS
      #   value: This should be set in Render dashboard

      - key: SPACY_DATA # <-- This one is a path, not a secret credential.
        value: /opt/render/project/src/.venv/share/spacy
