services:
  - type: web
    name: backend-results
    env: python
    buildCommand: "./post_deploy.sh"
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      # These variables should be set securely in the Render dashboard UI, NOT here.
      # - key: SENTRY_DSN
      #   value: This should be set in Render dashboard
      # - key: SENDER_EMAIL
      #   value: This should be set in Render dashboard
      # - key: EMAIL_APP_PASSWORD
      #   value: This should be set in Render dashboard
      # - key: FIREBASE_CREDENTIALS
      #   value: This should be set in Render dashboard

      # Render automatically provides the PORT environment variable.
      # You might explicitly define it here or in the dashboard for clarity, e.g.:
      - key: PORT
        value: 10000 # Render's default port.
      
      # SPACY_DATA is no longer explicitly needed by app.py, but remains if Render uses it internally.
      # However, since we're using /tmp, you can remove it if it was only for the old strategy.
      # If you keep it, ensure it's not pointing to /tmp (it should point to .venv if anything).
      # For now, let's omit it if you already have it in Render dashboard or you can remove it.
      # If you don't have it in the dashboard and it's not needed, remove it.
      # For simplicity, if you were managing SPACY_DATA in render.yaml, remove it now.
      # It's not part of this /tmp strategy.
      # - key: SPACY_DATA
      #   value: /opt/render/project/src/.venv/share/spacy
