services:
  - type: web
    name: backend-results
    env: python
    # Change buildCommand to use custom build.sh script
    buildCommand: "./post_deploy.sh" # CHANGED: Now using post_deploy.sh for build and spacy model download
    startCommand: gunicorn app:app
    envVars: []
