name: Python CI/CD Test

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-mock

    # New step to show us the exact content of the test file
    - name: Show Test File Content for Debugging
      run: |
        echo "--- Displaying content of tests/test_app.py ---"
        cat tests/test_app.py
        echo "--- End of file content ---"
      shell: bash

    - name: Run pytest
      run: |
        pytest
