name: Python CI/CD Test

# This tells GitHub to run this process on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use a standard virtual computer

    steps:
    # 1. Download the code from your repository
    - uses: actions/checkout@v3

    # 2. Set up the Python environment
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    # 3. Install all the necessary libraries
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-mock # Also install testing libraries

    # 4. Run the automated tests
    - name: Run pytest
      env:
        # *** THIS IS THE FIX ***
        # Provide a dummy value for the environment variable during the test.
        # This allows the app to be imported without crashing.
        # The tests themselves will mock the database, so this value is not actually used.
        FIREBASE_CREDENTIALS: "{}"
      run: |
        pytest
