name: Python CI/CD Test

# This tells GitHub to run this process on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use a standard virtual computer

    steps:
    # 1. Download the code from your repository
    - uses: actions/checkout@v3

    # 2. Set up the Python environment
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    # 3. Install all the necessary libraries
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-mock # Also install testing libraries

    # 4. Run the automated tests
    - name: Run pytest
      env:
        # *** THIS IS THE FIX ***
        # Provide a structurally valid dummy JSON object that satisfies all
        # of the Firebase Admin SDK's initial validation checks.
        FIREBASE_CREDENTIALS: '{"type": "service_account", "project_id": "test", "private_key": "test", "client_email": "test@example.com", "token_uri": "test"}'
      run: |
        pytest
