name: Python CI/CD Test

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-mock

    # Use a dedicated action to create the file reliably
    - name: Create dummy credential file
      uses: SpicyPizza/create-file-action@v2.0
      with:
        file_name: 'dummy-creds.json'
        file_content: ${{ secrets.DUMMY_FIREBASE_CREDS }}


    - name: Run pytest
      env:
        # Point to the credential file we just created
        GOOGLE_APPLICATION_CREDENTIALS: dummy-creds.json
      run: |
        pytest
