name: Run Daily Prediction Service

on:
  workflow_dispatch:
  schedule:
    # Runs at 2:00 AM UTC every day (7:30 AM IST)
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Firebase Credentials File
        # [MODIFIED] Using single quotes to preserve JSON formatting
        run: echo '${{ secrets.FIREBASE_CREDENTIALS }}' > firebase_credentials.json

      - name: Run Predictive Service
        run: python predictive_service.py
